### ISSUE TITLE
Image Support

### ISSUE THREAD

**Issue by aflorenzan** [ragunathjawahar/instant-adapter#1]
Does the InstantAdapter support to load an image into an ImageView?

**Comment by ragunathjawahar** [comment]
You can use evaluators to do anything you can do using a standard custom list adapter. This is not documented, but you can get an idea by looking into the source. @InstantImage is definitely on the list. It will come with features such as caching and lazy loading.

**Comment by aflorenzan** [comment]
Great! Thanks for your quick answer. I'll dig inside the code.

**Comment by ChristopheVersieux** [comment]
Killer feature would be to make @InstantImage compatible with Picasso: https://github.com/square/picasso

**Comment by ragunathjawahar** [comment]
@ChristopheVersieux, it's definitely on my list. You'll be able to plug in any library or your own implementation. That's how it's currently being designed :)

**Comment by tasomaniac** [comment]
+1 on compatibility with Picasso. I will definitely use this lib if it is compatible with it.

**Comment by ragunathjawahar** [comment]
Watch this video on how to add image support.

http://youtube.com/watch?v=TL85wXq_Ev4

**Comment by meredrica** [comment]
Could you also provide this information in text format? 10 minutes of video are just too much.

**Comment by ragunathjawahar** [comment]
@meredrica I will create a wiki and document this feature so that it would be easier for future references. Also instant adapter has been migrated to the [Adapter Kit](https://github.com/mobsandgeeks/adapter-kit) project. So, please use that from now on.
