### ISSUE TITLE
App does not support views inherited from TextView

### ISSUE THREAD

**Issue by thubalek** [ragunathjawahar/instant-adapter#2]
I found that adapter does not support classes inherited from TextView (eg. RobotoTextView).

Fortunately fix is easy. 

In class InstantAdapterCore (around line 300) you simply change this fragment of code from

```
Class<? extends View> viewType = holder.view.getClass();
if (viewType.isAssignableFrom(TextView.class)) {
      updateTextView(holder, returnValue);
}
```

to

```
Class<? extends View> viewType = holder.view.getClass();
if (TextView.class.isAssignableFrom(viewType)) {
      updateTextView(holder, returnValue);
}
```

**Comment by ragunathjawahar** [comment]
@thubalek Thank you for contributing. Please check the referenced commit.
